[workspace]
authors = ["Giovanni Dejan <giovanni.dejan@binus.ac.id>"]
channels = ["conda-forge"]
name = "python-pixi-template"
platforms = [{ name = "default", platform = "linux-64", cuda = "12.8" }, { name = "cicd", platform = "linux-64" }]
version = "0.1.0"

[tasks]
train = "python3 train.py"
lint-ci = "ruff check ."
lint-fix = "ruff check . --fix"
type-check = "mypy ."

[dependencies]
python = ">=3.13,<3.14"
mypy = ">=1.19.1,<2"
ruff = ">=0.15.5,<0.16"
pytest = ">=9.0.2,<10"
pre-commit = ">=4.5.1,<5"
torchvision = "=0.25.0"
torchview = ">=0.2.6,<0.3"
pillow = ">=12.3.0,<13"
torchinfo = ">=1.8.0,<2"
scikit-learn = ">=1.9.0,<2"
pandas = ">=3.0.5,<4"
matplotlib = ">=3.11.1,<4"
seaborn = ">=0.13.2,<0.14"
graphviz = ">=14.1.2,<15"

[target.default.dependencies]
pytorch-gpu = "=2.10.0"

[target.cicd.dependencies]
pytorch-cpu = "=2.10.0"

[pypi-dependencies]
mcp-pypi = ">=3.0.0, <4"
pyqt6 = ">=6.9.1, <7"
tqdm = ">=4.70.0, <5"
albumentations = ">=2.0.8, <3"
